AWSTemplateFormatVersion: 2010-09-09
###############################################################################################################
#                         AccessData - Full FTK Suite Cloud Formation v 2.0.0.0                               #
# Installs the entire FTK suite from an S3 Distribution - Must use the Unbundled Installer(s)                 #
# This script is region independent as long as it can reach the S3 Endpoint and the AMIs are cut correctly    #
# Verion History:                                                                                             #
#     Version:        Date:           Author            Notes                                                 #
#     2.0.0           May 22 2020     swharr            Intial Release                                        #
#                                                                                                             #
#                                                                                                             #
###############################################################################################################
Description: This stack deployes an AccessData Forensic Tools Environment (Distributed or Stand Alone) in a Private Cloud Environment. 
Parameters: 
  S3BucketName:
    Type: String
    Description: S3 Bucket where bits are stored. 
    Default: ad-swdistro
  SecurityGroupID:
    Type: String
    Description: Assign an existing security group to your deployment
    Default: sg-0c89c15d42d1bf602
  InstanceSize:
    Type: String
    Description: Select the Instance for your environment. (such as r5.xlarge)
    Default: r5.xlarge
    AllowedValues:
    - c5d.xlarge
    - c5d.2xlarge
    - c5d.4xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - r5.xlarge
    - r5.2xlarge
    - r5.4xlarge
    - c5.xlarge
    - c5.2xlarge
    - c5.4xlarge
  AmiID:
    Type: String
    Decription: Select the base AMI to use for the deployment
    